### ISSUE TITLE
Unable to re-install app after removal

### ISSUE THREAD

**Issue by msitekkie** [thebearmay/hubitat#23]
When configuring the backup schedule after adding the times (it wasn't clear if this was the time of day the backup & purge should run).
Initially I tried to run without times (left fields blank) & saw errors in the logs. After adding times 4 (backup) and 4.30 (purge) the app would no longer open so I could not try different parameters.
Tried to remove & re install the app, but it now refuses to install when I click Next in Hubitat Package Manager, there is no response.

**Comment by thebearmay** [comment]
If you didn’t remove the app from HPM it won’t re-install because it thinks you already have the code. If you just removed the app from the installed app list, the code is still there and you can re-add the application as an User App.  If you also deleted the code, go into HPM | Settings | Remove and select the app - this will remove it from HPM’s installed code list, and you should be goo d to go.
